In [3]:
import time
import numpy as np


In [2]:
x =np.random.random(10000000)

In [4]:
start = time.time()
sum(x)/len(x)
print(time.time()-start)

0.8648679256439209


In [5]:
start = time.time()
np.mean(x)
print(time.time()-start)

0.010284185409545898


In [6]:
x = np.array([1,2,3,4,5])

In [8]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
x.dtype                    # additional advantage of numpy that it handle more datatype than pytho

dtype('int64')

In [10]:
x.shape

(5,)

In [12]:
y=np.array([[1,2,5],[4,5,6],[7,6,9],[7,8,9]])
print(y)

[[1 2 5]
 [4 5 6]
 [7 6 9]
 [7 8 9]]


In [13]:
y.shape


(4, 3)

In [14]:
y.size

12

In [16]:
x= np.array(['Hello','World'])
print(x)

['Hello' 'World']


In [22]:
print("shape:",x.shape)
print("size:",x.size)
print("typoe",type(x))
print("dtype:",x.dtype)   #element are created uni charater

shape: (2,)
size: 2
typoe <class 'numpy.ndarray'>
dtype: <U5


In [24]:
x =np.array([1,2,"world"])
print(x)
print("size:",x.size)
print("typoe",type(x))
print("dtype:",x.dtype) 


['1' '2' 'world']
size: 3
typoe <class 'numpy.ndarray'>
dtype: <U21


In [26]:
x =np.array([1,2.5,5])
print(x)
print("size:",x.size)
print("typoe",type(x))
print("dtype:",x.dtype) 


[1.  2.5 5. ]
size: 3
typoe <class 'numpy.ndarray'>
dtype: float64


In [28]:
x =np.array([1,2.5,5],dtype=np.int64)  # you can explicitly change the data type for mixed array take care of precison
print(x)
print("size:",x.size)
print("type",type(x))
print("dtype:",x.dtype) 

[1 2 5]
size: 3
typoe <class 'numpy.ndarray'>
dtype: int64


In [32]:
x = np.array([1,2,3])     # it is able to save the array
np.save('my_array',x)

In [35]:
y = np.load('my_array.npy')    #you can lo0ad the value of array the you saved
print(y)

[1 2 3]


In [38]:
my_list =[1,4,5,7,8]      #generating numpy arrray through python list
np.array(my_list)

array([1, 4, 5, 7, 8])

In [40]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
print("dtype:",x.dtype)   # by default the datatype is float64

dtype: float64


In [45]:
x = np.zeros((3,4),dtype=int)   #you can change dtype in this way
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [46]:
x = np.ones((7,8))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [50]:
x = np.full((7,8),5)
print(x)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


In [51]:
x = np.full((7,8),5,dtype=int)
print(x)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


In [52]:
print("dtype:",x.dtype) 

dtype: int64


In [54]:
x = np.eye(5)   # it create identity mattrix
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [57]:
x = np.diag([10,20,30,40])  # it creat diagonal matrix
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [58]:
x = np.arange(10)  # it is ending value with one argument
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
x = np.arange(4,10)   # it is initial and ending with excluding ending
print(x)

[4 5 6 7 8 9]


In [64]:
x = np.arange(1,14,3)  # third argument show the different
print(x)

[ 1  4  7 10 13]


In [65]:
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [70]:
x = np.linspace(0,25,10,endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [72]:
x = np.arange(20) # it arange in single array diamention
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [78]:
x = np.reshape(x,(10,2))  # it is able to reshap the arange array
print(x)                  #but take care of the elements

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [79]:
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [80]:
x = np.reshape(x,(5,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [88]:
Y = np.arange(20).reshape((10,2))     
print(Y)
                                        #some function applied as method with (.)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [90]:
x = np.linspace(0,50,10,endpoint=False).reshape(5,2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [96]:
X = np.random.random((3,3 )) # it generates random nimber using numpy random function
print(X)

[[0.79310977 0.76560425 0.00234138]
 [0.64237422 0.34390656 0.74311383]
 [0.12181123 0.20089841 0.67992563]]


In [98]:
x = np.random.randint(4,15,(3,2))   # random integer with particular interval
print(x)

[[ 5  6]
 [ 5  7]
 [10 10]]


In [102]:
x = np.random.normal(0,0.1,size=(1000,1000))
print(x)

[[ 0.17192307 -0.22145394  0.02150133 ...  0.10285094  0.00103176
   0.01139195]
 [ 0.11523941  0.01290704  0.15253624 ...  0.0360405  -0.22547705
   0.00071775]
 [ 0.01415016  0.05006148 -0.09311584 ...  0.14480432  0.02842526
  -0.01598415]
 ...
 [ 0.01350417  0.17331654  0.09681347 ... -0.03943125 -0.08878669
   0.09182154]
 [ 0.08102313  0.15422924 -0.13376579 ... -0.06210602  0.08708562
   0.11814357]
 [-0.02322617 -0.13944798  0.22443283 ... -0.02386472 -0.2294232
   0.02316545]]


In [111]:
print("mean:",x.mean())
print("std:",x.std())
print("max:",x.max())
print("min:",x.min())
print("# positive:",(x>0).sum())
print("# Negative:",(x<0).sum())

mean: -7.132560431127914e-05
std: 0.09986990219248719
max: 0.5217514963058355
min: -0.5050979367531776
# positive: 500166
# Negative: 499834


In [5]:
import numpy as np
x = np.array([1,2,3,4,5])  #It wil help in data training
print(x)

[1 2 3 4 5]


In [6]:
print('1st element:',x[0])
print('2st element:',x[1])
print('4st element:',x[4])


1st element: 1
2st element: 2
4st element: 5


In [8]:
print('1st element:',x[-5])
print('2st element:',x[-4])
print('4st element:',x[-1])


1st element: 1
2st element: 2
4st element: 5


In [9]:
x[3]= 20
print(x)

[ 1  2  3 20  5]


In [15]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print("Elemenr at(0,0):",x[0,0])
print("Element at (0,1):",x[0,1])
print("Element at (2,2)",x[2,2])

Elemenr at(0,0): 1
Element at (0,1): 2
Element at (2,2) 9


In [18]:
x[0,0]=20

In [19]:
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [20]:
x= np.delete(x,[0,4])
print(x)

[2 3 4 6 7 8 9]


In [21]:
x =np.append(x,[7,8])
print(x)

[2 3 4 6 7 8 9 7 8]


In [22]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
w = np.append(y,[[10,12,14]],axis=0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 14]]


In [26]:
v = np.append(w,[[10,12,14]],axis=0)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 14]
 [10 12 14]]


In [30]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [33]:
w= np.insert(y,1,[4,5,6],axis=0)         # insert row betn the matrix
print(w)

[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [34]:
#array stacking started here
x = np.array([1,2])
print(x)

[1 2]


In [38]:
y = np.array([[4,5],[7,5]])
print(y)

[[4 5]
 [7 5]]


In [40]:
z=np.vstack((x,y))   # here we stack x on the top of y
print(z)

[[1 2]
 [4 5]
 [7 5]]


In [41]:
#slicing in ndarray
#1.ndarray[start:end]
#2.ndarray[start:]
#3.ndarray[:end]

In [42]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [43]:
z=x[1:4 ,2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [45]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [46]:
z=x[:3,2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [48]:
z = x[:,2]
print(z)

[ 3  8 13 18]


In [50]:
z= x[:,2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [51]:
indices = np.array(([1,3]))
print(indices)

[1 3]


In [53]:
y = x[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [56]:
z = x[:,indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [57]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [58]:
print(x[x<7])   # #instead of the indexes we use boolean

[0 1 2 3 4 5 6]


In [59]:
print(x[(x>10) & (x<17)])

[11 12 13 14 15 16]


In [60]:
x[(x>10) & (x<17)] = -1

In [61]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [65]:
x = np.array([1,2,4,6,8])
y=np.array([7,5,8,7,9])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))


[8]
[1 2 4 6]
[1 2 4 5 6 7 8 9]


In [68]:
x= np.random.randint(1,11,size=(10,))
print(x)

[4 4 7 3 8 7 1 6 6 6]


In [69]:
print(np.sort(x))
print(x)

[1 3 4 4 6 6 6 7 7 8]
[4 4 7 3 8 7 1 6 6 6]


In [70]:
print(np.sort(np.unique(x)))
print(x)

[1 3 4 6 7 8]
[4 4 7 3 8 7 1 6 6 6]


In [71]:
x.sort()
print(x)

[1 3 4 4 6 6 6 7 7 8]


In [72]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [74]:
x= np.random.randint(1,11,size=(10,10))
print(x)

[[ 8 10  2  1  2  3 10  8  5  6]
 [10  6  9  7  1  6  2  7 10  9]
 [ 2  9  5  4  3  8  7  1  1  6]
 [ 3  5  3  1  6  8  7  2  8  3]
 [ 9  3  2 10 10  5  3  7  8  9]
 [ 8  5  4  3  8  2 10  3  9  1]
 [ 1  9 10  9  3  4  5  8 10  2]
 [ 5  6  6  2  4  8  6  8  4  8]
 [ 8  8  7  5  2  8  7 10 10  6]
 [ 3  3  3  3  1 10  5  4  8  9]]


In [75]:
print(np.sort(x,axis=0))            #sort it vertical


[[ 1  3  2  1  1  2  2  1  1  1]
 [ 2  3  2  1  1  3  3  2  4  2]
 [ 3  5  3  2  2  4  5  3  5  3]
 [ 3  5  3  3  2  5  5  4  8  6]
 [ 5  6  4  3  3  6  6  7  8  6]
 [ 8  6  5  4  3  8  7  7  8  6]
 [ 8  8  6  5  4  8  7  8  9  8]
 [ 8  9  7  7  6  8  7  8 10  9]
 [ 9  9  9  9  8  8 10  8 10  9]
 [10 10 10 10 10 10 10 10 10  9]]


In [79]:
print(np.sort(x,axis=1))               #sort it horizontal

[[ 1  2  2  3  5  6  8  8 10 10]
 [ 1  2  6  6  7  7  9  9 10 10]
 [ 1  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  3  3  5  6  7  8  8]
 [ 2  3  3  5  7  8  9  9 10 10]
 [ 1  2  3  3  4  5  8  8  9 10]
 [ 1  2  3  4  5  8  9  9 10 10]
 [ 2  4  4  5  6  6  6  8  8  8]
 [ 2  5  6  7  7  8  8  8 10 10]
 [ 1  3  3  3  3  4  5  8  9 10]]


In [80]:
#Arithmatic operatiomn on array
#Element wise operation
#Metrix operation


In [81]:
#Element wise operation

x=np.array([1,2,3,4])
y= np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [83]:
print(x+y)
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [91]:
#subtract
print(x-y)
print(np.subtract(x,y))



[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [92]:
#multiply
print(x*y)
print(np.multiply(x,y))


[ 5 12 21 32]
[ 5 12 21 32]


In [93]:

#Divide

print(x/y)
print(np.divide(x,y))

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [96]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [98]:
y = np.array([5,6,7,8]).reshape(2,2)
print(y)

[[5 6]
 [7 8]]


In [99]:
print(x+y)

[[ 6  8]
 [10 12]]


In [100]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [101]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [102]:

print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [103]:
print(x)

[[1 2]
 [3 4]]


In [105]:
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [106]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [110]:
print(np.exp(x,))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [111]:
print(np.power(x,2))

[ 1  4  9 16]


In [112]:
print(np.power(x,3))

[ 1  8 27 64]


In [113]:
y = np.array([5,6,7,8]).reshape(2,2)
print(y)

[[5 6]
 [7 8]]


In [123]:
print("avarage of all:",y.mean())

avarage of all: 6.5


In [120]:

print("avarage of colomns:",x.mean(axis=0))

avarage of colomns: 2.5


In [124]:
print("avarage of rows:",y.mean(axis=1))

avarage of rows: [5.5 7.5]


In [130]:
print("sum of all:" , x.sum())
print("sum of column:",x.sum(axis=0))


sum of all: 10
sum of column: 10


In [131]:
print("sum of row:", y.sum(axis=1))

sum of row: [11 15]


In [137]:
#statistical operation
x.std()

1.118033988749895

In [134]:
np.median(x)

2.5

In [135]:
x.max()

4

In [136]:
x.min()

1

In [138]:
print(x)

[1 2 3 4]


In [139]:
y = np.array([5,6,7,8]).reshape(2,2)
print(y)


[[5 6]
 [7 8]]


In [141]:
print(3+y)

[[ 8  9]
 [10 11]]


In [144]:
print(y-3)

[[2 3]
 [4 5]]


In [145]:
print(y*3)

[[15 18]
 [21 24]]


In [146]:
print(y/y)

[[1. 1.]
 [1. 1.]]


In [147]:
print(y/3)

[[1.66666667 2.        ]
 [2.33333333 2.66666667]]
